### ISSUE TITLE
Doesn't work with gnome-shell 3.31.90

### ISSUE THREAD

**Issue by jbicha** [JasonLG1979/gnome-shell-extensions-mediaplayer#474]
- Ubuntu 19.04 Alpha
- gnome-shell 3.31.90
- gnome-shell-extension-mediaplayer 4.0 (from the Debian/Ubuntu package)

The mediaplayer extension doesn't work with gnome-shell 3.31.

In looking glass, I see these errors:

```
TypeError: this._construct is not a function
TypeError: manager is undefined
```

**Comment by JasonLG1979** [comment]
1. This extension is pretty much on it's last leg. Eventually many of it's features will be cherry picked, streamlined and eventually added to  https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button and it will be put out to pasture and shot.

2. I'm not going to mess around with a Ubuntu alpha to test against a beta version of GNOME. When Ubuntu 19.04 (stable) comes out with GNOME 3.32 (stable) I will test against it.

**Comment by JasonLG1979** [comment]
See https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/478
